# Generated by Django 5.2.12 on 2026-08-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0078_orden_estado_delivery_orden_repartidor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_activo', models.BooleanField(default=True, verbose_name='Gestión de Salón')),
                ('cocina_activo', models.BooleanField(default=True, verbose_name='Pantalla KDS')),
                ('inventario_activo', models.BooleanField(default=True, verbose_name='Control de Inventario')),
                ('delivery_activo', models.BooleanField(default=True, verbose_name='Módulo Delivery')),
                ('clientes_activo', models.BooleanField(default=True, verbose_name='Directorio CRM')),
                ('facturacion_activo', models.BooleanField(default=True, verbose_name='Facturación Electrónica')),
                ('carta_qr_activo', models.BooleanField(default=True, verbose_name='Menú Digital QR')),
                ('bot_wsp_activo', models.BooleanField(default=True, verbose_name='Bot WhatsApp')),
                ('ml_activo', models.BooleanField(default=True, verbose_name='Predicciones IA')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interruptor global de módulos',
                'verbose_name_plural': 'Interruptor global de módulos',
            },
        ),
    ]
