# Generated by Django 5.2.12 on 2026-08-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0080_ticketsoporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPagoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yape_numero', models.CharField(blank=True, default='', max_length=15)),
                ('yape_titular', models.CharField(blank=True, default='', max_length=100)),
                ('plin_numero', models.CharField(blank=True, default='', max_length=15)),
                ('plin_titular', models.CharField(blank=True, default='', max_length=100)),
                ('banco', models.CharField(blank=True, default='', max_length=50)),
                ('numero_cuenta', models.CharField(blank=True, default='', max_length=30)),
                ('cci', models.CharField(blank=True, default='', max_length=30)),
                ('titular_cuenta', models.CharField(blank=True, default='', max_length=100)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos de pago de la plataforma',
                'verbose_name_plural': 'Datos de pago de la plataforma',
            },
        ),
        migrations.AddField(
            model_name='pagosuscripcion',
            name='captura_pago',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/pagos_suscripcion/'),
        ),
    ]
