# Generated by Django 5.2.12 on 2026-08-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0081_datospagoplataforma_pagosuscripcion_captura_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='telefono_propietario',
            field=models.CharField(blank=True, default='', help_text='Celular del dueño para contactarlo directo (no es el WhatsApp del bot de ninguna sede).', max_length=20),
        ),
    ]
