# Generated by Django 5.2.12 on 2026-08-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0082_negocio_telefono_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='dni_propietario',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='negocio',
            name='nombre_propietario',
            field=models.CharField(blank=True, default='', help_text='Nombre completo del dueño (RENIEC) — no es la razón social del negocio.', max_length=150),
        ),
    ]
