# Generated by Django 5.2.12 on 2026-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0083_negocio_dni_propietario_negocio_nombre_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansaas',
            name='modulo_clientes',
            field=models.BooleanField(default=False, help_text='¿Incluye el directorio CRM?'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='modulo_facturacion',
            field=models.BooleanField(default=False, help_text='¿Incluye facturación electrónica SUNAT?'),
        ),
    ]
