# Generated by Django 5.2.12 on 2026-09-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0084_plansaas_modulo_clientes_plansaas_modulo_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionvariacion',
            name='modo_stock',
            field=models.CharField(choices=[('receta', 'Receta (insumos y cantidades)'), ('unidad', 'Por unidad')], default='receta', max_length=10),
        ),
    ]
