# Generated by Django 5.2.12 on 2026-09-04 22:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0085_opcionvariacion_modo_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('proveedor', 'Compra a Proveedor'), ('interno', 'Reabastecimiento Interno')], max_length=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('solicitado', 'Solicitado'), ('confirmado', 'Confirmado'), ('en_camino', 'En Camino'), ('recibido_parcial', 'Recibido Parcial'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('fecha_pedido', models.DateTimeField(blank=True, null=True)),
                ('fecha_estimada', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('whatsapp_enviado', models.BooleanField(default=False)),
                ('whatsapp_enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_creadas', to='negocios.empleado')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='negocios.negocio')),
                ('sede_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_recibidas', to='negocios.sede')),
                ('sede_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_solicitadas', to='negocios.sede')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('costo_unitario_referencial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insumo_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_orden_compra', to='negocios.insumobase')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='negocios.ordencompra')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, help_text='WhatsApp del proveedor', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='negocios.negocio')),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='negocios.proveedor'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['negocio', 'estado'], name='negocios_or_negocio_03f236_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['sede_destino', 'estado'], name='negocios_or_sede_de_d9cedb_idx'),
        ),
    ]
