# Generated by Django 5.2.12 on 2026-09-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0086_ordencompra_ordencompradetalle_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='avatar_propietario',
            field=models.ImageField(blank=True, help_text='Foto de perfil del dueño/administrador, mostrada en el topbar del ERP.', null=True, upload_to='negocios/avatars/'),
        ),
    ]
