# Generated by Django 5.2.12 on 2026-09-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0087_negocio_avatar_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ultima_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
