# Generated by Django 5.2.12 on 2026-09-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0088_empleado_ultima_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='bot_token',
            field=models.CharField(blank=True, default='', help_text='Secreto propio de esta sede para BotTokenAuthentication (n8n). Se genera solo; NUNCA se comparte entre sedes/negocios.', max_length=64),
        ),
    ]
