# Generated by Django 5.2.12 on 2026-09-09 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0090_backfill_sede_bot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bot_recordatorio_enviado',
            field=models.BooleanField(default=False, help_text="Ya se le mandó el recordatorio de 'seguimos con tu pedido' para esta sesión inactiva."),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bot_ultima_actividad',
            field=models.DateTimeField(blank=True, help_text='Última vez que cotizó un pedido por el bot. La marca cotizar_bot.', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bot_ultima_sede',
            field=models.ForeignKey(blank=True, help_text='Sede (y por lo tanto instancia de WhatsApp) de esa última actividad.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.sede'),
        ),
    ]
