# Generated by Django 5.2.12 on 2026-09-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0091_cliente_bot_recordatorio_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='notas_cocina',
            field=models.TextField(blank=True, null=True),
        ),
    ]
