# Generated by Django 5.2.12 on 2026-09-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0092_orden_notas_cocina'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='carta_modo',
            field=models.CharField(choices=[('propia', 'Nuestra Carta Digital'), ('pdf', 'PDF Propio'), ('link', 'Link Externo')], default='propia', help_text='Qué le manda el bot al cliente cuando pide el menú.', max_length=10),
        ),
    ]
