# Generated by Django 5.2.12 on 2026-09-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0093_sede_carta_modo'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='tipo_negocio',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('tienda', 'Tienda')], default='restaurante', max_length=20),
        ),
    ]
